Module2 task2
htmlacademy-adaptive/186928-pognali-21 pull request #4
Opened 2020-12-06 20:45 UTC by KazbekGit

2020-12-07 17:48 UTC, ElseeCCD requested changes

2020-12-07 17:48 UTC, ElseeCCD commented on source/form.html
> +      <nav class="main-nav modal visually-hidden">
что тут делает блок modal?

2020-12-07 17:48 UTC, ElseeCCD commented on source/form.html
> +          <div class="plans-step__duration-block">
чем, кроме содержимого, отличаются plans-step__companion-block и plans-step__duration-block? Мне кажется, что это один и тот же блок, но с разным содержимым

2020-12-07 17:48 UTC, ElseeCCD commented on source/form.html
> +          <div class="calendar">
календарик логичнее было бы сделать таблицей, тогда и без стилей отображался бы адекватно

2020-12-07 17:48 UTC, ElseeCCD commented on source/form.html
> +          <input class="plans-step__children" type="checkbox" name="children" id="children" />
А если я захочу добавить точно такой же чекбокс для животных? Будем создавать отдельный класс?

2020-12-07 17:48 UTC, ElseeCCD commented on source/form.html
> +              <li class="calendar__day calendar__day--weekday">С</li>
weekday - это будний день. Наверно, хотел написать weekend

2020-12-07 17:48 UTC, ElseeCCD commented on source/form.html
> +            <ul class="countries-block__countries-list visually-hidden modal">
а тут что делает modal?

2020-12-07 17:48 UTC, ElseeCCD commented on source/form.html
> +          <input class="plans-step__choose-country" type="text" placeholder="ДОБАВИТЬ СТРАНУ" id="add-country" />
назови лучше более абстрактно. add-button, что-нибудь такое

2020-12-07 17:48 UTC, ElseeCCD commented on source/form.html
> +        <button class="plans-step__submit" for="add-plans-form" type="submit">Отправить</button>
мне кажется, что кнопка "Следующий шаг", например, выглядит точно так же. Почему классы разные?

2020-12-07 17:48 UTC, ElseeCCD commented on source/index.html
> +<head>
что произошло? Почему в index нет изменений из мастера?

2020-12-07 21:56 UTC, KazbekGit commented on source/index.html
> +<head>
Это самый сложный вопрос из всех заданных  вчера тобою вопросов. У меня нет на него ответа. Сейчас попробую исправить, погуглю

2020-12-08 05:56 UTC, KazbekGit commented on source/form.html
> +      <nav class="main-nav modal visually-hidden">
Удалил блок. Нет его. И не будет больше )

2020-12-08 05:57 UTC, KazbekGit commented on source/form.html
> +          <div class="plans-step__duration-block">
И, вправду, ничем. Только кода больше. Объединил в один блок.

2020-12-08 05:57 UTC, KazbekGit commented on source/form.html
> +          <div class="calendar">
Сказано - сделано. Таблица на месте. И числа в ней - тоже

2020-12-08 05:58 UTC, KazbekGit commented on source/form.html
> +          <input class="plans-step__children" type="checkbox" name="children" id="children" />
Нет, не будем.
 "plans-step__checkbox" подойдет сюда гораздо лучше )

2020-12-08 05:58 UTC, KazbekGit commented on source/form.html
> +              <li class="calendar__day calendar__day--weekday">С</li>
Спасибо, исправил )

2020-12-08 05:59 UTC, KazbekGit commented on source/form.html
> +            <ul class="countries-block__countries-list visually-hidden modal">
И отсюда удалил.

2020-12-08 05:59 UTC, KazbekGit commented on source/form.html
> +          <input class="plans-step__choose-country" type="text" placeholder="ДОБАВИТЬ СТРАНУ" id="add-country" />
Назвал. Абстрактно. Именно add-button и назвал )

2020-12-08 06:00 UTC, KazbekGit commented on source/form.html
> +        <button class="plans-step__submit" for="add-plans-form" type="submit">Отправить</button>
Да, согласен. Одно и то же, просто у одних кнопок есть бэкграунд, а у других его нет

2020-12-08 20:07 UTC, ElseeCCD approved these changes

2020-12-08 20:08 UTC, merged

2020-12-09 09:59 UTC, KazbekGit commented on source/form.html
> +              <th class="calendar__days-list">
Да да, конечно. Исправлю