Разметка страницы каталога
htmlacademy-adaptive/186928-pognali-21 pull request #5
Opened 2020-12-09 19:51 UTC by KazbekGit

2020-12-12 16:39 UTC, ElseeCCD requested changes

2020-12-12 16:39 UTC, ElseeCCD commented on source/form.html
> +              <td class="calendar__days-list">
нет, tr должен быть, не td. td - это для ячеек таблицы, tr - для строк. Тут строка.
Ты бы это заметил, если бы не забывал прогонять свои странички через валидатор: https://validator.w3.org/
Прогони все, везде есть ошибки.

2020-12-12 16:39 UTC, ElseeCCD commented on source/catalog.html
> +    <h1 class="main__header">Попутчики</h1>
давай лучше main__title назовем

2020-12-12 16:39 UTC, ElseeCCD commented on source/catalog.html
> +        <input сlass="companion-preferences__music-checkbox" type="checkbox" name="heavy-rock" checked><span>Тяжелый
в "хобби" и "еда" будут точно такие же чекбоксы. Назови лучше filter-checkbox

2020-12-12 16:39 UTC, ElseeCCD commented on source/catalog.html
> +    <form class="companion-preferences" action="https://echo.htmlacademy.ru" method="POST" id="find-companion">
companion-preferences - это слишком конкретно. Давай лучше назови блок filters или как-нибудь так, более абстрактно

2020-12-12 16:39 UTC, ElseeCCD commented on source/catalog.html
> +        <h3 class="user-card__user-name">Таня Фирсова</h3>
не надо повторяться, `user-card__name` вполне достаточно

2020-12-12 16:39 UTC, ElseeCCD commented on source/catalog.html
> +        <p class="user-card__user-hobbies">
`user-card__hobbies` достаточно

2020-12-12 16:39 UTC, ElseeCCD commented on source/catalog.html
> +        <button class="call-user" type="button">ПОЗВАТЬ</button>
давай кнопку тоже абстрактнее назовем. 
Вообще, мне кажется, что у кнопок "Авторизация", "Показать", "Повать" очень ммного общего. Я бы создала отдельный блок button, куда бы вынесла все общие стили, а различия оформляла бы модификаторами: button--auth, button--filters, button--action и т.д.

2020-12-12 18:42 UTC, KazbekGit commented on source/form.html
> +              <td class="calendar__days-list">
ok... валидатор. Буду проверять

2020-12-12 18:42 UTC, KazbekGit commented on source/catalog.html
> +    <h1 class="main__header">Попутчики</h1>
ok

2020-12-13 17:35 UTC, ElseeCCD approved these changes

2020-12-13 17:36 UTC, merged